import json
import os

# Load spec from file generated by triage.py
with open('spec.json', 'r', encoding='utf-8') as f:
    spec = json.load(f)

with open('index.html', 'r') as f:
    content = f.read()

# Task: Add reset button if in spec
if any("reset button" in task.lower() for task in spec['tasks']):
    if '<button onclick="resetCounter()">' not in content:
        content = content.replace('</div>', '<button onclick="resetCounter()">Reset</button></div>')
        content += '\n        <script>function resetCounter() { count = 0; updateDisplay(); }</script>'

# Task: Ensure responsiveness (already added, but verify)
if not '@media' in content and 'responsive' in spec['scope'].lower():
    content = content.replace('</style>', '@media (max-width: 600px) { .controls { flex-direction: column; gap: 5px; } button { width: 100%; margin: 5px 0; } }</style>')

with open('index.html', 'w') as f:
    f.write(content)

# Commit and push
os.system('git add index.html && git commit -m "Update per spec tasks" && git push')
